### PR TITLE
Bundler pkg

### PR DESCRIPTION
**Pull request by torhector2**
I can only conform the Mac app works on my x86 Mac, someone has to try on Win and Linux.

image

### CODE REVIEW

**Comment by hernandoagf** [comment]
Tried on:
- MacOS with M1 processor
- Windows with x64 processor

And it worked on both

**Comment by adamgoth** [comment]
Were you able to use the executable that was created? It's not working for me on macOS. 

`Error: Cannot find module 'open'`

I'll dig into it a bit more later.

**Comment by adamgoth** [comment]
> It's not working for me on macOS with intel i7 processor.
> 
> `Error: Cannot find module 'open'`
> 
> I'll dig into it a bit more later.

After reinstalling all deps, I'm back to the original error, even with the new targets

```
> pkg@5.8.1
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  %1: node_modules/open/xdg-open
  %2: path-to-executable/xdg-open
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  %1: node_modules/open/xdg-open
  %2: path-to-executable/xdg-open
```

I'll try later on another machine to see if it changes anything.

**Comment by torhector2** [comment]
@adamgoth Did you get an error or just the warnings? is there any executable in the folder?

**Review by b-pmcg — APPROVED** [review]

**Comment by b-pmcg** [comment]
I got the warnings too, but the bundle was still created in `apps/bundler-webapp/bundles` folder, and the executable worked for me

**Comment by adamgoth** [comment]
> I got the warnings too, but the bundle was still created in `apps/bundler-webapp/bundles` folder, and the executable worked for me

Confirming it's the same for me. I'll merge this.

**Pull request merged**
